// 错误码定义
// 格式：{模块}_{错误类型}

export const ERROR_CODES = {
  // 通用
  UNKNOWN: 'UNKNOWN',
  INVALID_PARAMS: 'INVALID_PARAMS',

  // 资产相关
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_UPLOAD_FAILED: 'ASSET_UPLOAD_FAILED',
  ASSET_INVALID_TYPE: 'ASSET_INVALID_TYPE',

  // Track 相关
  TRACK_NOT_FOUND: 'TRACK_NOT_FOUND',
  TRACK_ALREADY_GENERATING: 'TRACK_ALREADY_GENERATING',
  TRACK_NO_INPUT: 'TRACK_NO_INPUT',

  // Job 相关
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_ALREADY_RUNNING: 'JOB_ALREADY_RUNNING',

  // 生成相关
  GEN_AUDIO_CHECK_FAILED: 'GEN_AUDIO_CHECK_FAILED',
  GEN_AUDIO_TOO_SHORT: 'GEN_AUDIO_TOO_SHORT',
  GEN_AUDIO_TOO_LONG: 'GEN_AUDIO_TOO_LONG',
  GEN_PROVIDER_ERROR: 'GEN_PROVIDER_ERROR',
  GEN_PROVIDER_TIMEOUT: 'GEN_PROVIDER_TIMEOUT',

  // 分享相关
  SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
  SHARE_EXPIRED: 'SHARE_EXPIRED',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

// 错误信息映射（可用于 i18n）
export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  UNKNOWN: '未知错误',
  INVALID_PARAMS: '参数校验失败',

  ASSET_NOT_FOUND: '资产不存在',
  ASSET_UPLOAD_FAILED: '上传失败',
  ASSET_INVALID_TYPE: '不支持的文件类型',

  TRACK_NOT_FOUND: '作品不存在',
  TRACK_ALREADY_GENERATING: '作品正在生成中',
  TRACK_NO_INPUT: '缺少输入音频',

  JOB_NOT_FOUND: '任务不存在',
  JOB_ALREADY_RUNNING: '任务已在运行',

  GEN_AUDIO_CHECK_FAILED: '音频校验失败',
  GEN_AUDIO_TOO_SHORT: '音频时长过短',
  GEN_AUDIO_TOO_LONG: '音频时长过长',
  GEN_PROVIDER_ERROR: '生成服务异常',
  GEN_PROVIDER_TIMEOUT: '生成服务超时',

  SHARE_NOT_FOUND: '分享链接不存在',
  SHARE_EXPIRED: '分享链接已过期',
}
